import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { css } from "../../styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={css({
          display: "initial",
        })}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
